[package]
name = "awkernel_display"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
embedded-graphics = "0.8"

[dependencies.awkernel_async_lib]
path = "../../awkernel_async_lib"
default-features = false

[dependencies.awkernel_lib]
path = "../../awkernel_lib"
default-features = false
