[package]
name = "memory_fatfs_mount"
version = "0.1.0"
edition = "2021"

[dependencies]
awkernel_lib = { path = "../../../awkernel_lib" }
awkernel_async_lib = { path = "../../../awkernel_async_lib" }

[lib]
crate-type = ["cdylib"]