// General Register Descriptions
pub(super) const IGC_CTRL: usize = 0x00000; // Device Control - RW
pub(super) const IGC_STATUS: usize = 0x00008; // Device Status - RO
pub(super) const IGC_EECD: usize = 0x00010; // EEPROM/Flash Control - RW

// NVM  Register Descriptions
pub(super) const IGC_EERD: usize = 0x12014; // EEprom mode read - RW
pub(super) const IGC_EEWR: usize = 0x12018; // EEprom mode write - RW
pub(super) const IGC_CTRL_EXT: usize = 0x00018; // Extended Device Control - RW
pub(super) const IGC_MDIC: usize = 0x00020; // MDI Control - RW
pub(super) const IGC_MDICNFG: usize = 0x00E04; // MDI Config - RW
pub(super) const IGC_FCAL: usize = 0x00028; // Flow Control Address Low - RW
pub(super) const IGC_FCAH: usize = 0x0002C; // Flow Control Address High -RW
pub(super) const IGC_I225_FLSWCTL: usize = 0x12048; // FLASH control register
pub(super) const IGC_I225_FLSWDATA: usize = 0x1204C; // FLASH data register
pub(super) const IGC_I225_FLSWCNT: usize = 0x12050; // FLASH Access Counter
pub(super) const IGC_I225_FLSECU: usize = 0x12114; // FLASH Security
pub(super) const IGC_FCT: usize = 0x00030; // Flow Control Type - RW
pub(super) const IGC_CONNSW: usize = 0x00034; // Copper/Fiber switch control - RW
pub(super) const IGC_VET: usize = 0x00038; // VLAN Ether Type - RW
pub(super) const IGC_ICR: usize = 0x01500; // Intr Cause Read - RC/W1C
pub(super) const IGC_ITR: usize = 0x000C4; // Interrupt Throttling Rate - RW
pub(super) const IGC_ICS: usize = 0x01504; // Intr Cause Set - WO
pub(super) const IGC_IMS: usize = 0x01508; // Intr Mask Set/Read - RW
pub(super) const IGC_IMC: usize = 0x0150C; // Intr Mask Clear - WO
pub(super) const IGC_IAM: usize = 0x01510; // Intr Ack Auto Mask- RW
pub(super) const IGC_RCTL: usize = 0x00100; // Rx Control - RW
pub(super) const IGC_FCTTV: usize = 0x00170; // Flow Control Transmit Timer Value
pub(super) const IGC_TXCW: usize = 0x00178; // Tx Configuration Word - RW
pub(super) const IGC_RXCW: usize = 0x00180; // Rx Configuration Word - RO
pub(super) const IGC_EICR: usize = 0x01580; // Ext. Interrupt Cause Read - R/clr
pub(super) const IGC_EITR: fn(usize) -> usize = |n| 0x01680 + (0x4 * n);
pub(super) const IGC_EICS: usize = 0x01520; // Ext. Interrupt Cause Set - W0
pub(super) const IGC_EIMS: usize = 0x01524; // Ext. Interrupt Mask Set/Read - RW
pub(super) const IGC_EIMC: usize = 0x01528; // Ext. Interrupt Mask Clear - WO
pub(super) const IGC_EIAC: usize = 0x0152C; // Ext. Interrupt Auto Clear - RW
pub(super) const IGC_EIAM: usize = 0x01530; // Ext. Interrupt Ack Auto Clear Mask
pub(super) const IGC_GPIE: usize = 0x01514; // General Purpose Interrupt Enable - RW
pub(super) const IGC_IVAR0: usize = 0x01700; // Interrupt Vector Allocation (array) - RW
pub(super) const IGC_IVAR_MISC: usize = 0x01740; // IVAR for "other" causes - RW
pub(super) const IGC_TCTL: usize = 0x00400; // Tx Control - RW
pub(super) const IGC_TCTL_EXT: usize = 0x00404; // Extended Tx Control - RW
pub(super) const IGC_TIPG: usize = 0x00410; // Tx Inter-packet gap -RW
pub(super) const IGC_AIT: usize = 0x00458; // Adaptive Interframe Spacing Throttle - RW
pub(super) const IGC_LEDCTL: usize = 0x00E00; // LED Control - RW
pub(super) const IGC_LEDMUX: usize = 0x08130; // LED MUX Control
pub(super) const IGC_EXTCNF_CTRL: usize = 0x00F00; // Extended Configuration Control
pub(super) const IGC_EXTCNF_SIZE: usize = 0x00F08; // Extended Configuration Size
pub(super) const IGC_PHY_CTRL: usize = 0x00F10; // PHY Control Register in CSR
pub(super) const IGC_PBA: usize = 0x01000; // Packet Buffer Allocation - RW
pub(super) const IGC_PBS: usize = 0x01008; // Packet Buffer Size
pub(super) const IGC_EEMNGCTL: usize = 0x01010; // MNG EEprom Control
pub(super) const IGC_EEMNGCTL_I225: usize = 0x01010; // i225 MNG EEprom Mode Control
pub(super) const IGC_EEARBC_I225: usize = 0x12024; // EEPROM Auto Read Bus Control
pub(super) const IGC_FLOP: usize = 0x0103C; // FLASH Opcode Register
pub(super) const IGC_WDSTP: usize = 0x01040; // Watchdog Setup - RW
pub(super) const IGC_SWDSTS: usize = 0x01044; // SW Device Status - RW
pub(super) const IGC_FRTIMER: usize = 0x01048; // Free Running Timer - RW
pub(super) const IGC_TCPTIMER: usize = 0x0104C; // TCP Timer - RW
pub(super) const IGC_ERT: usize = 0x02008; // Early Rx Threshold - RW
pub(super) const IGC_FCRTL: usize = 0x02160; // Flow Control Receive Threshold Low - RW
pub(super) const IGC_FCRTH: usize = 0x02168; // Flow Control Receive Threshold High - RW
pub(super) const IGC_PSRCTL: usize = 0x02170; // Packet Split Receive Control - RW
pub(super) const IGC_RDFH: usize = 0x02410; // Rx Data FIFO Head - RW
pub(super) const IGC_RDFT: usize = 0x02418; // Rx Data FIFO Tail - RW
pub(super) const IGC_RDFHS: usize = 0x02420; // Rx Data FIFO Head Saved - RW
pub(super) const IGC_RDFTS: usize = 0x02428; // Rx Data FIFO Tail Saved - RW
pub(super) const IGC_RDFPC: usize = 0x02430; // Rx Data FIFO Packet Count - RW
pub(super) const IGC_PBRTH: usize = 0x02458; // PB Rx Arbitration Threshold - RW
pub(super) const IGC_FCRTV: usize = 0x02460; // Flow Control Refresh Timer Value - RW
