#!/bin/bash

LTLS=(eventually_prerequisites ensure_priority)
CPU_NUMS=(2 3)

clear
for CPU_NUM in "${CPU_NUMS[@]}"; do
    echo "=== Running verification for CPU_NUM=$CPU_NUM ==="

    for LTL in "${LTLS[@]}"; do
        spin -DCPU_NUM=$CPU_NUM -a preemptive.pml
        gcc -O3 -DCOLLAPSE -DVECTORSZ=5000 -DNFAIR=3 -o pan pan.c
        rm -f *.trail
        ./pan -a -N"$LTL" -n -m30000
    done
done
