[package]
name = "x86bootdisk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.11"
ovmf-prebuilt = "0.1.0-alpha.1"
clap = { version = "4.2", features = ["derive"] }
home = "0.5"
