name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 13 * * 1"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust nightly
        run: rustup toolchain install nightly-2026-07-20
      - name: Use Rust nightly
        run: rustup default nightly-2026-07-20
      - name: Add Rust components
        run: rustup component add rust-src llvm-tools-preview clippy rustfmt
      - name: Add Rust targets
        run: rustup target add x86_64-unknown-none aarch64-unknown-none riscv32imac-unknown-none-elf riscv64gc-unknown-none-elf
      - name: Install libssl1.1
        run: wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb && sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb
      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - name: Install cargo-binutils
        run: cargo binstall cargo-binutils -y
      - name: Install cargo-udeps
        run: cargo binstall cargo-udeps -y

      - name: Check
        run: scripts/ci.sh
